package qpx

// generated by JSON-to-go
type Response struct {
	Kind  string `json:"kind"`
	Trips struct {
		Kind      string `json:"kind"`
		RequestId string `json:"requestId"`
		Data      struct {
			Kind    string `json:"kind"`
			Airport []struct {
				Kind string `json:"kind"`
				Code string `json:"code"`
				City string `json:"city"`
				Name string `json:"name"`
			} `json:"airport"`
			City []struct {
				Kind string `json:"kind"`
				Code string `json:"code"`
				Name string `json:"name"`
			} `json:"city"`
			Aircraft []struct {
				Kind string `json:"kind"`
				Code string `json:"code"`
				Name string `json:"name"`
			} `json:"aircraft"`
			Tax []struct {
				Kind string `json:"kind"`
				Id   string `json:"id"`
				Name string `json:"name"`
			} `json:"tax"`
			Carrier []struct {
				Kind string `json:"kind"`
				Code string `json:"code"`
				Name string `json:"name"`
			} `json:"carrier"`
		} `json:"data"`
		TripOption []struct {
			Kind      string `json:"kind"`
			SaleTotal string `json:"saleTotal"`
			Id        string `json:"id"`
			Slice     []struct {
				Kind     string `json:"kind"`
				Duration int    `json:"duration"`
				Segment  []struct {
					Kind     string `json:"kind"`
					Duration int    `json:"duration"`
					Flight   struct {
						Carrier string `json:"carrier"`
						Number  string `json:"number"`
					} `json:"flight"`
					Id                  string `json:"id"`
					Cabin               string `json:"cabin"`
					BookingCode         string `json:"bookingCode"`
					BookingCodeCount    int    `json:"bookingCodeCount"`
					MarriedSegmentGroup string `json:"marriedSegmentGroup"`
					Leg                 []struct {
						Kind                string `json:"kind"`
						Id                  string `json:"id"`
						Aircraft            string `json:"aircraft"`
						ArrivalTime         string `json:"arrivalTime"`
						DepartureTime       string `json:"departureTime"`
						Origin              string `json:"origin"`
						Destination         string `json:"destination"`
						DestinationTerminal string `json:"destinationTerminal"`
						Duration            int    `json:"duration"`
						OperatingDisclosure string `json:"operatingDisclosure"`
						Mileage             int    `json:"mileage"`
						Secure              bool   `json:"secure"`
					} `json:"leg"`
					ConnectionDuration int `json:"connectionDuration"`
				} `json:"segment"`
			} `json:"slice"`
			Pricing []struct {
				Kind string `json:"kind"`
				Fare []struct {
					Kind        string `json:"kind"`
					Id          string `json:"id"`
					Carrier     string `json:"carrier"`
					Origin      string `json:"origin"`
					Destination string `json:"destination"`
					BasisCode   string `json:"basisCode"`
				} `json:"fare"`
				SegmentPricing []struct {
					Kind              string `json:"kind"`
					FareId            string `json:"fareId"`
					SegmentId         string `json:"segmentId"`
					FreeBaggageOption []struct {
						Kind          string `json:"kind"`
						BagDescriptor []struct {
							Kind           string   `json:"kind"`
							CommercialName string   `json:"commercialName"`
							Count          int      `json:"count"`
							Description    []string `json:"description"`
							Subcode        string   `json:"subcode"`
						} `json:"bagDescriptor"`
						Pieces int `json:"pieces"`
					} `json:"freeBaggageOption"`
				} `json:"segmentPricing"`
				BaseFareTotal string `json:"baseFareTotal"`
				SaleFareTotal string `json:"saleFareTotal"`
				SaleTaxTotal  string `json:"saleTaxTotal"`
				SaleTotal     string `json:"saleTotal"`
				Passengers    struct {
					Kind       string `json:"kind"`
					AdultCount int    `json:"adultCount"`
				} `json:"passengers"`
				Tax []struct {
					Kind       string `json:"kind"`
					Id         string `json:"id"`
					ChargeType string `json:"chargeType"`
					Code       string `json:"code"`
					Country    string `json:"country"`
					SalePrice  string `json:"salePrice"`
				} `json:"tax"`
				FareCalculation     string `json:"fareCalculation"`
				LatestTicketingTime string `json:"latestTicketingTime"`
				Ptc                 string `json:"ptc"`
			} `json:"pricing"`
		} `json:"tripOption"`
	} `json:"trips"`
}
